In [1]:
import polars as pl
import numpy as np
import pandas as pd

In [2]:
pl.show_versions()

--------Version info---------
Polars:              1.31.0
Index type:          UInt32
Platform:            Windows-10-10.0.26100-SP0
Python:              3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
LTS CPU:             False

----Optional dependencies----
Azure CLI            <not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           <not installed>
deltalake            <not installed>
fastexcel            <not installed>
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           <not installed>
numpy                2.3.2
openpyxl             3.1.5
pandas               2.3.1
polars_cloud         <not installed>
pyarrow              21.0.0
pydantic             <not installed>
pyiceb

In [3]:
csvFile = "data/titanic.csv"
df = pl.read_csv(csvFile)
df.head(3)

shape: (3, 12)
┌─────────────┬──────────┬────────┬─────────────────────────────────┬───┬──────────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                            ┆ … ┆ Ticket           ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---                             ┆   ┆ ---              ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str                             ┆   ┆ str              ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═════════════════════════════════╪═══╪══════════════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen Harris         ┆ … ┆ A/5 21171        ┆ 7.25    ┆ null  ┆ S        │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs. John Bradley (Fl… ┆ … ┆ PC 17599         ┆ 71.2833 ┆ C85   ┆ C        │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss. Laina          ┆ … ┆ STON/O2. 3101282 ┆ 7.925   ┆ null  ┆ S        │
└─────────────┴──────────┴────────┴─────────────────────────────────┴───┴──────────────────┴─────────┴───────┴──────────┘

In [4]:
arr = df.to_numpy()
arr

array([[1, 0, 3, ..., 7.25, None, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, None, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, None, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, None, 'Q']], shape=(891, 12), dtype=object)

In [5]:
floats_array = (
    df
    .select(
        pl.col(pl.Float64)
    )
    .to_numpy()
)
floats_array.dtype

dtype('float64')

In [7]:
rand_array = np.random.standard_normal((5, 3))
(
    pl.DataFrame(
        rand_array
    )
)

shape: (5, 3)
┌───────────┬───────────┬───────────┐
│ column_0  ┆ column_1  ┆ column_2  │
│ ---       ┆ ---       ┆ ---       │
│ f64       ┆ f64       ┆ f64       │
╞═══════════╪═══════════╪═══════════╡
│ -0.097378 ┆ 0.64754   ┆ 0.730612  │
│ -0.152459 ┆ -1.269021 ┆ 0.945818  │
│ 1.106789  ┆ 1.590421  ┆ -0.37264  │
│ -0.059715 ┆ 1.91535   ┆ 2.718509  │
│ 0.14557   ┆ -0.652771 ┆ -0.621653 │
└───────────┴───────────┴───────────┘

In [9]:
df["Age"].head().to_numpy()

array([22., 38., 26., 35., 35., nan, 54.,  2., 27., 14.])

In [11]:
arr = (
    df["Survived"]
    .head()
    .to_numpy(zero_copy_only=True)
)
arr

C:\Users\yk279\AppData\Local\Temp\ipykernel_10572\551642388.py:4: DeprecationWarning: the `zero_copy_only` parameter for `Series.to_numpy` is deprecated. Use the `allow_copy` parameter instead, which is the inverse of `zero_copy_only`.
(Deprecated in version 0.20.10)
  .to_numpy(zero_copy_only=True)


array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1])

In [13]:
arr = (
    df["Survived"]
    .head()
    .to_numpy(zero_copy_only=True)
)
arr[0] = 100

C:\Users\yk279\AppData\Local\Temp\ipykernel_10572\1997275621.py:4: DeprecationWarning: the `zero_copy_only` parameter for `Series.to_numpy` is deprecated. Use the `allow_copy` parameter instead, which is the inverse of `zero_copy_only`.
(Deprecated in version 0.20.10)
  .to_numpy(zero_copy_only=True)


ValueError: assignment destination is read-only

In [14]:
(
    df
    .to_pandas()
    .head(2)
)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500  None        S  
1      0   PC 17599  71.2833   C85        C

In [16]:
(
    df
    .to_pandas(use_pyarrow_extension_array=True)
    .head(2)
)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171     7.25  <NA>        S  
1      0   PC 17599  71.2833   C85        C

In [20]:
df.to_pandas(use_pyarrow_extension_array=False).dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [21]:
df.to_pandas(use_pyarrow_extension_array=True).dtypes

PassengerId           int64[pyarrow]
Survived              int64[pyarrow]
Pclass                int64[pyarrow]
Name           large_string[pyarrow]
Sex            large_string[pyarrow]
Age                  double[pyarrow]
SibSp                 int64[pyarrow]
Parch                 int64[pyarrow]
Ticket         large_string[pyarrow]
Fare                 double[pyarrow]
Cabin          large_string[pyarrow]
Embarked       large_string[pyarrow]
dtype: object